strictness: veryhigh
doc-warnings: true

pylint:
      disable:
            - unnecessary-lambda
            - line-too-long
            - unused-argument
            - import-self
            - too-many-arguments
            - too-many-locals
            - pointless-string-statement
            - pointless-except
            - broad-except
            - invalid-name
            - too-few-public-methods
            - global-statement
            - attribute-defined-outside-init
            - no-self-use
            - too-many-instance-attributes
            - import-error
            - wrong-import-order

pep8:
      disable:
            - E501
            - W503
            - W191
            - N802
            - E126

pep257:
      disable:
            - D402
